version: '3'
networks:
  airflow_con:
    driver: bridge
services:
  app:
    build: .
    volumes:
      - ./OpenAQDataPlatform:/OpenAQDataPlatform
    environment:
      - PYTHONPATH=/OpenAQDataPlatform
  airflow:
    image: apache/airflow:latest
    networks:
      - airflow_con
    ports:
      - "8080:8080"
    volumes:
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./OpenAQDataPlatform:/opt/airflow/OpenAQDataPlatform
      - ./api_utilities:/opt/airflow/api_utilities
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://myuser:mypassword@timescaledb:5432/mydatabase
      - PYTHONPATH=/opt/airflow
      - OPENAQ_API_KEY=bbaf6f880e46663bc05c83eab3c2c7460b6771c63c1e76a06ed8dff6acf002ed
      - TSDB_URI=postgresql://myuser:mypassword@timescaledb:5432/mydatabase
    depends_on:
      - timescaledb
    command: 
         bash -c "airflow db init && airflow users create \
                           --username admin \
                           --password admin \
                           --firstname FIRST_NAME \
                           --lastname LAST_NAME \
                           --role Admin \
                           --email admin@example.org && \
                            airflow webserver &&
                            airflow scheduler"

         bash -c "pip install -r /requirements.txt"
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    networks:
      - airflow_con
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    command:
      - --max_connections=300
      - --shared_buffers=1GB
      - --work_mem=50MB
      - --maintenance_work_mem=1GB
      - --effective_cache_size=3GB
      - --timescaledb.max_background_workers=8
      - --timescaledb.telemetry_level=off
      - --listen_addresses=*
    ports:
    - "5432:5432"
