version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    command: pytest tests/
  airflow:
    image: apache/airflow:latest
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://myuser:mypassword@timescaledb:5432/mydatabase
    depends_on:
      - timescaledb
    command: bash -c "airflow db init && airflow users create \
                           --username admin \
                           --password admin \
                           --firstname FIRST_NAME \
                           --lastname LAST_NAME \
                           --role Admin \
                           --email admin@example.org && \
                            airflow webserver &&
                            airflow scheduler"
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
    - "5433:5432"
